### ISSUE TITLE
renderForeground content goes beyond bounds when pulling down

### ISSUE THREAD

**Issue by nHiRanZ** [i6mi6/react-native-parallax-scroll-view#105]
Contents of the `renderForeground` method tends scroll out of bounds when pulling down on the scroll. Looks unnatural that way. Any way to fix this?

**Comment by Li357** [comment]
Is this the same bug as referenced here?

https://github.com/i6mi6/react-native-parallax-scroll-view/pull/109

**Comment by nHiRanZ** [comment]
@Li357 Yes. Closing.
