### ISSUE TITLE
Not comatible with iphone X, XS screens

### ISSUE THREAD

**Issue by jakubgrzelak** [i6mi6/react-native-parallax-scroll-view#116]
Unfortunately the package is not compatible with iPhone X and XS screens. There is always a background on the top and it is not possible to get rid of it ( or am I mistaken? ) Regards

**Comment by fungilation** [comment]
Wrap it in your own View with safe top/bottom margins.

**Comment by acollazomayer** [comment]
@fungilation this should not be closed! it is not compatible for iphone x, xs screens. the image is overlaping the status bar. adding a view with top margin is not working either. and wrapping it in a safe area view niether

**Comment by wowtrxqn** [comment]
> @fungilation this should not be closed! it is not compatible for iphone x, xs screens. the image is overlaping the status bar. adding a view with top margin is not working either. and wrapping it in a safe area view niether

how to fix?
