### ISSUE TITLE
How to prevent scroll content from overflowing into fixed header?

### ISSUE THREAD

**Issue by tleewu** [i6mi6/react-native-parallax-scroll-view#123]
Hi I'm trying to use the `renderFixedHeader` method, but I'm having some trouble with the child component overlapping with the header. See image below.

![image](https://user-images.githubusercontent.com/7733219/54048402-8c81f780-418e-11e9-8d10-db8716c186cc.png)

Wondering if I'm missing a gotcha here.

**Comment by tleewu** [comment]
Closing this... decided to do a sticky header instead

**Comment by rp-nova** [comment]
nooo, it's still an issue and today I'm facing this, should this issue reopen?
