### ISSUE TITLE
decrease the height of the overall scroll view

### ISSUE THREAD

**Issue by iSimar** [i6mi6/react-native-parallax-scroll-view#27]
Even if I don't have anything inside the parallaxscrollview, there is still a lot of white space that's scrollable, how can i change the height size of the overall parallaxscrollview?

**Comment by judgejab** [comment]
Any updates on this?

**Comment by iEricKoh** [comment]
Same problem.

**Comment by AE0011** [comment]
just set marginBottom of parallaxScrollView equal to header height: (**_minus_**)
<ParallaxScrollView
    style={{marginBottom: -STICKY_HEADER_HEIGHT}}
    ....

**Comment by bahaa96** [comment]
Is there any solution ?

**Comment by jankoritak** [comment]
Bump, still seems unsolved.

**Comment by bahaa96** [comment]
@jankoritak There's a PR solving this issue and it's working properly. It's not merged yet so you might need to clone it separately.

**Comment by jankoritak** [comment]
@bahaa96 Could you, please, link me the PR?

Btw. I ended up resolving it by patching (removing) `footerSpacer`, which seems to work in my case.

**Comment by johhansantana** [comment]
If you use `stickyHeaderHeight={100}` for example, it will add like a padding top when you scroll so it doesn't scroll all the way to the top. Increasing the number will increase the padding where it stops scrolling.
