### ISSUE TITLE
npm publish 0.20.1

### ISSUE THREAD

**Issue by luisfuertes** [i6mi6/react-native-parallax-scroll-view#85]
Im trying to install `react-native-parallax-scroll-view@0.20.1` but:
![captura de pantalla 2017-09-27 a las 15 55 03](https://user-images.githubusercontent.com/18212615/30917420-4334355c-a39c-11e7-981a-3432911c3052.png)

Have you forgotten to do npm publish?

**Comment by rubensbarreto** [comment]
Same here

**Comment by kadoshms** [comment]
+1

**Comment by i6mi6** [comment]
Published
